SELECT * FROM restaurant;
---------------
INSERT INTO Restaurant (rest_name, cuisine, city)
VALUES
  ('Dulce', 'Mexican', 'Atlanta'),
  ('Boost BBQ', 'BBQ', 'Chicago'),
  ('China Wok', 'Chinese', 'New York City'),
  ('China Max', 'Chinese', 'Dallas'),
  ('Papa Murphys', 'Italian', 'Houston'),
  ('China Gourmet', 'Chinese', 'Los Angeles'),
  ('Reggies Pizza', 'Italian', 'Seattle'),
  ('Taco Bueno', 'Mexican', 'New York City'),
  ('The Cheesecake Factory', 'American', 'Seattle'),
  ('Casa di Pasta', 'Italian', 'Chicago'),
  ('Thai-licious', 'Thai', 'Miami'),
  ('Q-Time BBQ', 'BBQ', 'San Diego'),
  ('The Great Gatsby Steakhouse', 'American', 'Dallas'),
  ('The Wok-N-Roll', 'Chinese', 'Miami'),
  ('Reggie''s Pita', 'Greek', 'Atlanta'),
  ('Taco-Mania', 'Mexican', 'San Diego'),
  ('Papa Luigi''s Pizza', 'Italian', 'Chicago'),
  ('Siam Square Thai', 'Thai', 'Miami'),
  ('Smokey''s BBQ Joint', 'BBQ', 'San Diego'),
  ('The Italian Job', 'Italian', 'Chicago'),
  ('Taco Inn', 'Mexican', 'New York City'),
  ('P.F. Chang''s', 'Chinese', 'Dallas'),
  ('China Bistro', 'Chinese', 'Los Angeles'),
  ('China Dynasty', 'Chinese', 'Houston'),
  ('Taco Land', 'Mexican', 'Los Angeles'),
  ('China Palace', 'Chinese', 'Los Angeles'),
  ('Taco Bell Grande', 'Mexican', 'New York City'),
  ('Red Lobster', 'American', 'Seattle'),
  ('China Express', 'Chinese', 'Seattle'),
  ('The Big Apple Diner', 'American', 'New York City'),
  ('Taco-licious', 'Mexican', 'Orlando'),
  ('Thai-Thai', 'Thai', 'Los Angeles'),
  ('The Italian Spot', 'Italian', 'Houston'),
  ('The BBQ Barn', 'American', 'Dallas'),
  ('Taco Town', 'Mexican', 'New York City'),
  ('Thai Express', 'Thai', 'Dallas'),
  ('Mama''s Oven', 'Italian', 'Los Angeles'),
  ('The BBQ Grill', 'American', 'Houston'),
  ('Taco-Mania', 'Mexican', 'Seattle'),
  ('Thai-Thai Express', 'Thai', 'New York City'),
  ('The Italian Kitchen', 'Italian', 'Orlando'),
  ('The BBQ Pit', 'American', 'Los Angeles'),
  ('Taco-Rific', 'Mexican', 'Houston'),
  ('Thai-Licious Bistro', 'Thai', 'Seattle'),
  ('The Italian Trattoria', 'Italian', 'New York City'),
  ('The BBQ Cafe', 'American', 'Orlando'),
  ('Taco-Mania Express', 'Mexican', 'Los Angeles'),
  ('Thai-Thai Bistro', 'Thai', 'Houston'),
  ('Taco Bell', 'Mexican', 'Orlando'),
  ('Outback Steakhouse', 'American', 'Dallas'),
  ('Buffalo Wild Wings', 'American', 'Houston'),
  ('Taco Casa', 'Mexican', 'Houston'),
  ('Gregs Chinese', 'Chinese', 'Orlando'),
  ('The Hat', 'Greek', 'New York City'),
  ('Regal Chinese', 'Chinese', 'Houston'),
  ('Taco Cabana', 'Mexican', 'Seattle'),
  ('China Star', 'Chinese', 'Orlando'),
  ('Taco Time', 'Mexican', 'Dallas'),
  ('Taco del Mar', 'Mexican', 'Seattle'),
  ('Chick-fil-A', 'American', 'New York City'),
  ('Applebee''s', 'American', 'Seattle'),
  ('Regency Chinese', 'Chinese', 'New York City'),
  ('Olive Garden', 'Italian', 'Houston'),
  ('TGI Fridays', 'American', 'Los Angeles'),
  ('El Taco Loco', 'Mexican', 'Los Angeles'),
  ('Taco Tico', 'Mexican', 'Orlando'),
  ('Panera Bread', 'American', 'New York City'),
  ('China Garden', 'Chinese', 'Houston'),
  ('IHOP', 'American', 'Orlando'),
  ('Thai Express', 'Thai', 'Manhattan'),
  ('Tony''s BBQ', 'BBQ', 'Miami'),
  ('The Cheesecake Factory', 'Italian', 'Atlanta'),
  ('P.F. Chang''s', 'Thai', 'New Orleans'),
  ('Taco Bell', 'BBQ', 'San Francisco'),
  ('Pei Wei', 'Italian', 'Manhattan'),
  ('Olive Garden', 'Thai', 'Miami'),
  ('Red Lobster', 'BBQ', 'Atlanta'),
  ('Chipotle Mexican Grill', 'Thai', 'San Francisco'),
  ('Buffalo Wild Wings', 'Italian', 'Miami'),
  ('The Big Cheese', 'Italian', 'Dallas'),
  ('The American Grill', 'American', 'Atlanta'),
  ('The Italian Bakery', 'Italian', 'Boston'),
  ('The American Diner', 'American', 'Portland'),
  ('Brent''s Bistro', 'Italian', 'San Francisco'),
  ('Noted', 'Greek', 'Los Angeles'),
  ('The American Cafe', 'American', 'Miami'),
  ('Mario''s Trattoria', 'Italian', 'Atlanta'),
  ('The American Bistro', 'American', 'Boston'),
  ('The Italian Cafe', 'Italian', 'Portland'),
  ('Porto''s Steakhouse', 'American', 'Atlanta'),
  ('The American Burger Joint', 'American', 'Portland'),
  ('Maria''s Italian Kitchen', 'Italian', 'San Francisco'),
  ('Mel''s Drive-In', 'American', 'Miami'),
  ('Gio''s Bakery', 'Italian', 'Atlanta'),
  ('Sunnyside Cafe', 'American', 'Boston'),
  ('Zero Pizzeria', 'Italian', 'Portland'),
  ('Uno''s Kitchen', 'Greek', 'Portland'),
  ('The Kitchen Table', 'American', 'Los Angeles'),
  ('The Gourmet Grind', 'Greek', 'New York City'),
  ('De Leche', 'Mexican', 'Dallas'),
  ('China Max', 'Chinese', 'Dallas'),
  ('The Great Gatsby Steakhouse', 'American', 'Dallas'),
  ('P.F. Chang''s', 'Chinese', 'Dallas'),
  ('The BBQ Barn', 'American', 'Dallas'),
  ('Thai Express', 'Thai', 'Dallas'),
  ('Outback Steakhouse', 'American', 'Dallas'),
  ('Taco Time', 'Mexican', 'Dallas'),
  ('The Big Cheese', 'Italian', 'Dallas'),
  ('De Leche', 'Mexican', 'Dallas');